-- Чемпионат России 2026, Новосибирск, 2026-06-02—2026-06-06.
-- Сгенерировано scripts/gen_seed.py из data/chempionat-rossii-2026.json, не править руками.
-- Оцифрованы длинный цикл (толчок ДЦ), страницы 2-16, и толчок (мужчины) в весовых категориях 63 и 68 кг с отдельных страниц, номера которых в документе неизвестны. Остальные разделы протокола (толчок в прочих весовых категориях, рывок, жонглирование, командный зачёт) не извлекались.
-- Данные извлечены из скана протокола моделью; сверка человеком не проводилась,
-- поэтому results.verified_by остаётся пустым (FR-A14).

INSERT OR IGNORE INTO regions (name, country) VALUES
  ('Новосибирская область', 'RU'),
  ('Пермский край', 'RU'),
  ('Республика Бурятия', 'RU'),
  ('г. Санкт-Петербург', 'RU'),
  ('Калужская область', 'RU'),
  ('Ханты-Мансийский АО - Югра', 'RU'),
  ('Омская область', 'RU'),
  ('Томская область', 'RU'),
  ('г. Москва', 'RU'),
  ('Белгородская область', 'RU'),
  ('Кировская область', 'RU'),
  ('Челябинская область', 'RU'),
  ('Республика Саха (Якутия)', 'RU'),
  ('Республика Хакасия', 'RU'),
  ('Республика Татарстан', 'RU'),
  ('Ямало-Ненецкий автономный округ', 'RU'),
  ('Курганская область', 'RU'),
  ('Алтайский край', 'RU'),
  ('Оренбургская область', 'RU'),
  ('Вологодская область', 'RU'),
  ('Смоленская область', 'RU'),
  ('Ярославская область', 'RU'),
  ('Кемеровская область', 'RU'),
  ('Воронежская область', 'RU'),
  ('Брянская область', 'RU'),
  ('Архангельская область', 'RU'),
  ('Тюменская область', 'RU'),
  ('Республика Башкортостан', 'RU'),
  ('Чувашская Республика', 'RU');

INSERT OR IGNORE INTO clubs (name, region_id) VALUES
  ('ГАУ НСО «РЦСП СК и СР»', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')),
  ('МАУ ДО «СШ «Прикамье» г. Перми', (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU')),
  ('ВС РФ', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')),
  ('РОО ФГС г. САНКТ ПЕТЕРБУРГ', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')),
  ('МБУ ДО «Онохойская СШ»', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')),
  ('СДСШОР им. Краевского', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')),
  ('СШОР «Маршал»', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')),
  ('МБУ ДО СШОР «Югория» им. А.А. Пилояна', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')),
  ('МУ ДО «МЦРФКиС» Черепановского района', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')),
  ('РЦСП', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')),
  ('СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')),
  ('МАУ ДО «СШ №2» Сургутского района', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')),
  ('Спортивная школа №1 в Асино', (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU')),
  ('МБУ ДО «ДЮСШ «Спарт»', (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU')),
  ('РО ООО ВФГС в г. Москве', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')),
  ('РО ООО "ВФГС" в г. Москве', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')),
  ('МБУ ДО СШОР 5 г Белгород', (SELECT id FROM regions WHERE name = 'Белгородская область' AND country = 'RU')),
  ('СШОР Маршал', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')),
  ('КОГАУ "СШОР "Юность"', (SELECT id FROM regions WHERE name = 'Кировская область' AND country = 'RU')),
  ('РО ООО «ВФГС» в Челябинской области', (SELECT id FROM regions WHERE name = 'Челябинская область' AND country = 'RU')),
  ('Республиканский центр национальных видов спорта', (SELECT id FROM regions WHERE name = 'Республика Саха (Якутия)' AND country = 'RU')),
  ('Спортивная школа г. Черногорск', (SELECT id FROM regions WHERE name = 'Республика Хакасия' AND country = 'RU')),
  ('НГТУ', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')),
  ('"УСЗ Импульс" г. Буинск', (SELECT id FROM regions WHERE name = 'Республика Татарстан' AND country = 'RU')),
  ('ГБУ ДО МКСШОР «Запад» Отделение «Семёрка»', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')),
  ('МБУ ДО СШ «Зенит»', (SELECT id FROM regions WHERE name = 'Ямало-Ненецкий автономный округ' AND country = 'RU')),
  ('МБУДО "Варгашинская СШ"', (SELECT id FROM regions WHERE name = 'Курганская область' AND country = 'RU')),
  ('СШОРСВС им В.Ф. Краевского', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')),
  ('ВС РФ', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')),
  ('МБУДО "Каргапольская ДЮСШ"', (SELECT id FROM regions WHERE name = 'Курганская область' AND country = 'RU')),
  ('МУ ДО "МЦРФКиС" Черепановского района', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')),
  ('МАУ «РУСС»', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')),
  ('РО ООО "ВФГС" в Новосибирской области', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')),
  ('СШОР Кристалл', (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU')),
  ('Олимп', (SELECT id FROM regions WHERE name = 'Челябинская область' AND country = 'RU')),
  ('Федерация гиревого спорта Алтайского Края', (SELECT id FROM regions WHERE name = 'Алтайский край' AND country = 'RU')),
  ('ЦСП Омской области', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')),
  ('СШ №1 им. Л.Д. Ковалевского', (SELECT id FROM regions WHERE name = 'Оренбургская область' AND country = 'RU')),
  ('БУ ДО города Омска «СШОР №33»', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')),
  ('ФГС КО', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')),
  ('СШОР', (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU')),
  ('ВС РФ', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')),
  ('СШОР №3, г. Череповец', (SELECT id FROM regions WHERE name = 'Вологодская область' AND country = 'RU')),
  ('ГБУ ДО МКСШОР «Запад», отделение «Семёрка»', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')),
  ('КШС 1', (SELECT id FROM regions WHERE name = 'Смоленская область' AND country = 'RU')),
  ('ФГС ЯО', (SELECT id FROM regions WHERE name = 'Ярославская область' AND country = 'RU')),
  ('ДЮСШ Краснозерского района', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')),
  ('МБУ ДО СШ №3, г. Улан-Удэ', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')),
  ('КШС 1/ СГУС', (SELECT id FROM regions WHERE name = 'Смоленская область' AND country = 'RU')),
  ('МАУ ДО "КСШ КМО"', (SELECT id FROM regions WHERE name = 'Кемеровская область' AND country = 'RU')),
  ('КОГАУ "СШОР "Юность "', (SELECT id FROM regions WHERE name = 'Кировская область' AND country = 'RU')),
  ('РО ООО «ВФГС» в г. Москве', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')),
  ('ДОО(П)Ц "Юниор"', (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU')),
  ('МКУ ДО "Бобровская СШ имени В.Л. Паткина"', (SELECT id FROM regions WHERE name = 'Воронежская область' AND country = 'RU')),
  ('Федерация гиревого спорта Томской области', (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU')),
  ('МБУ ДО СШОР по борьбе', (SELECT id FROM regions WHERE name = 'Брянская область' AND country = 'RU')),
  ('САФУ Арктика', (SELECT id FROM regions WHERE name = 'Архангельская область' AND country = 'RU')),
  ('ТРО ООО «ВФГС»', (SELECT id FROM regions WHERE name = 'Тюменская область' AND country = 'RU')),
  ('РО ООО «ВФГС» в Омской области', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')),
  ('ССК «КИТ на спорте"', (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU')),
  ('КОГАУ «СШОР «Юность»', (SELECT id FROM regions WHERE name = 'Кировская область' AND country = 'RU')),
  ('МАУ ДО «Спортивная школа»', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')),
  ('спортивный клуб "АГАУ"', (SELECT id FROM regions WHERE name = 'Алтайский край' AND country = 'RU')),
  ('МАУ ДО СШОР', (SELECT id FROM regions WHERE name = 'Республика Башкортостан' AND country = 'RU')),
  ('РО ООО ВФГС в Челябинской области', (SELECT id FROM regions WHERE name = 'Челябинская область' AND country = 'RU')),
  ('ВС РФ', (SELECT id FROM regions WHERE name = 'Воронежская область' AND country = 'RU')),
  ('ФСК "Улап", СШ Энергия', (SELECT id FROM regions WHERE name = 'Чувашская Республика' AND country = 'RU')),
  ('ДЮСШ Кулундинского района', (SELECT id FROM regions WHERE name = 'Алтайский край' AND country = 'RU'));

INSERT OR IGNORE INTO federations (name, short_name, country) VALUES
  ('Всероссийская федерация гиревого спорта', 'ВФГС', 'RU');

INSERT INTO competitions (id, slug, name, date_start, date_end, city, country, competition_rank_id, federation_id, source_url, is_published) VALUES
  (1, 'chempionat-rossii-2026', 'Чемпионат России 2026', '2026-06-02', '2026-06-06', 'Новосибирск', 'RU', (SELECT id FROM competition_ranks WHERE code = 'national_ch'), (SELECT id FROM federations WHERE name = 'Всероссийская федерация гиревого спорта'), NULL, 1);

INSERT INTO protocols (id, competition_id, r2_key, filename, page_count, is_scan, status, published_at) VALUES
  (1, 1, 'protocols/chempionat-rossii-2026.pdf', 'Chempionat_Rossii_2026.pdf', 41, 1, 'published', '2026-06-02');

INSERT INTO categories (id, competition_id, discipline_id, sex, age_group_id, division_id, bell_kg, hands, time_limit_min, weight_class_raw, weight_class_kg, weight_class_is_open, participants_declared, is_deferred, sort_order) VALUES
  (1, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'm', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 32, 'two', 10, '63', 63, 0, 9, 0, 1),
  (2, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'm', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 32, 'two', 10, '68', 68, 0, 9, 0, 2),
  (3, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'm', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 32, 'two', 10, '73', 73, 0, 11, 0, 3),
  (4, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'm', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 32, 'two', 10, '78', 78, 0, 13, 0, 4),
  (5, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'm', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 32, 'two', 10, '85', 85, 0, 10, 0, 5),
  (6, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'm', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 32, 'two', 10, '95', 95, 0, 10, 0, 6),
  (7, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'm', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 32, 'two', 10, '95+', 95, 1, 8, 0, 7),
  (8, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'f', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 24, 'two', 10, '58', 58, 0, 8, 0, 8),
  (9, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'f', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 24, 'two', 10, '63', 63, 0, 6, 0, 9),
  (10, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'f', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 24, 'two', 10, '68', 68, 0, 7, 0, 10),
  (11, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'f', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 24, 'two', 10, '68+', 68, 1, 9, 0, 11),
  (12, 1, (SELECT id FROM disciplines WHERE code = 'jerk'), 'm', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 32, 'two', 10, '63', 63, 0, 11, 0, 12),
  (13, 1, (SELECT id FROM disciplines WHERE code = 'jerk'), 'm', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 32, 'two', 10, '68', 68, 0, 11, 0, 13),
  (14, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'm', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 32, 'two', 12, 'эстафета (мужчины)', NULL, 0, NULL, 1, 104),
  (15, 1, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 'f', (SELECT id FROM age_groups WHERE code = 'adult'), NULL, 24, 'two', 12, 'эстафета (женщины)', NULL, 0, NULL, 1, 105);

INSERT INTO athletes (id, last_name, first_name, middle_name, birth_year, sex, region_id, club_id, coach, sport_rank_id) VALUES
  (1, 'Бутенко', 'Евгений', 'Александрович', 1995, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ГАУ НСО «РЦСП СК и СР»' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Бутенко А.А.', (SELECT id FROM sport_ranks WHERE code = 'zms')),
  (2, 'Сиразетдинов', 'Данил', 'Ильфатович', 2007, 'm', (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ ДО «СШ «Прикамье» г. Перми' AND region_id = (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU')), 'Мошев Д.И., Ческис О.И.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (3, 'Якушев', 'Роман', 'Владимирович', 2002, 'm', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ВС РФ' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')), 'Любимский С.А., Алексеев В.И.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (4, 'Руднев', 'Руслан', 'Сергеевич', 1994, 'm', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РОО ФГС г. САНКТ ПЕТЕРБУРГ' AND region_id = (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')), 'Руднев С.Л.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (5, 'Недорезов', 'Василий', 'Сергеевич', 1992, 'm', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО «Онохойская СШ»' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')), 'Рассадин А.А., Леонов С.Т.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (6, 'Жбанов', 'Алексей', 'Александрович', 1986, 'm', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СДСШОР им. Краевского' AND region_id = (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')), 'Барков А.П.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (7, 'Кормилицын', 'Иван', 'Николаевич', 2010, 'm', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР «Маршал»' AND region_id = (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')), 'Пянко И.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (8, 'Жалов', 'Ярослав', 'Борисович', 2007, 'm', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШОР «Югория» им. А.А. Пилояна' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Шпартко М.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (9, 'Филатов', 'Алексей', 'Александрович', 2008, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МУ ДО «МЦРФКиС» Черепановского района' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Бутенко И.А.', (SELECT id FROM sport_ranks WHERE code = 'i')),
  (10, 'Морозович', 'Владислав', 'Павлович', 1999, 'm', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РЦСП' AND region_id = (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')), 'Сагандыков К.К.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (11, 'Рыжков', 'Антон', 'Николаевич', 1994, 'm', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского' AND region_id = (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')), 'Талибов А.Х.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (12, 'Захаров', 'Кирилл', 'Дмитриевич', 2007, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МУ ДО «МЦРФКиС» Черепановского района' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Бутенко И.А.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (13, 'Коломин', 'Дмитрий', 'Андреевич', 1999, 'm', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО «Онохойская СШ»' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')), 'Рассадин А.А., Хлебодаров А.Г., Леонов С.Т.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (14, 'Хамидов', 'Фахриддин', 'Фарход угли', 2002, 'm', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР «Маршал»' AND region_id = (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')), 'Барбакова Н.А.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (15, 'Сергеев', 'Алексей', 'Вячеславович', 2001, 'm', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ ДО «СШ №2» Сургутского района' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Трофимова А.А, Садыков Р.И.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (16, 'Рыбский', 'Павел', 'Сергеевич', 2008, 'm', (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'Спортивная школа №1 в Асино' AND region_id = (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU')), 'Бажин А.М.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (17, 'Мелюхин', 'Кирилл', 'Александрович', 2011, 'm', (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО «ДЮСШ «Спарт»' AND region_id = (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU')), 'Маматов Г.Т.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (18, 'Сидоренков', 'Александр', 'Александрович', 2010, 'm', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РО ООО ВФГС в г. Москве' AND region_id = (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')), 'Соловьев А.В.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (19, 'Беляев', 'Иван', 'Сергеевич', 1992, 'm', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШОР «Югория» им. А.А. Пилояна' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Шпартко М.А., Власов А.П., Меркулин С.В.', (SELECT id FROM sport_ranks WHERE code = 'zms')),
  (20, 'Рябков', 'Алексей', 'Игоревич', 1993, 'm', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШОР «Югория» им. А.А. Пилояна' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Шпартко М.А., Алтухов Д.В.', (SELECT id FROM sport_ranks WHERE code = 'zms')),
  (21, 'Багров', 'Максим', 'Дмитриевич', 2009, 'm', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РО ООО "ВФГС" в г. Москве' AND region_id = (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')), 'Соловьёв А.В.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (22, 'Фомин', 'Фёдор', 'Алексеевич', 2004, 'm', (SELECT id FROM regions WHERE name = 'Белгородская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШОР 5 г Белгород' AND region_id = (SELECT id FROM regions WHERE name = 'Белгородская область' AND country = 'RU')), 'Меркулин С.В.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (23, 'Трофимов', 'Тимур', 'Михайлович', 2011, 'm', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР Маршал' AND region_id = (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')), 'Пянко И.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (24, 'Новоселов', 'Андрей', 'Евгеньевич', 2004, 'm', (SELECT id FROM regions WHERE name = 'Кировская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'КОГАУ "СШОР "Юность"' AND region_id = (SELECT id FROM regions WHERE name = 'Кировская область' AND country = 'RU')), 'Малков Е.И.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (25, 'Семенов', 'Никита', 'Андреевич', 1993, 'm', (SELECT id FROM regions WHERE name = 'Челябинская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РО ООО «ВФГС» в Челябинской области' AND region_id = (SELECT id FROM regions WHERE name = 'Челябинская область' AND country = 'RU')), 'Симушин А.М.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (26, 'Рожин', 'Егор', 'Иннокентьевич', 1987, 'm', (SELECT id FROM regions WHERE name = 'Республика Саха (Якутия)' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'Республиканский центр национальных видов спорта' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Саха (Якутия)' AND country = 'RU')), 'Кардашевский Н.С.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (27, 'Жибинов', 'Фёдор', 'Васильевич', 2004, 'm', (SELECT id FROM regions WHERE name = 'Республика Хакасия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'Спортивная школа г. Черногорск' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Хакасия' AND country = 'RU')), 'Жибинов К.В., Жибинов В.В.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (28, 'Колоколов', 'Никита', 'Александрович', 2007, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'НГТУ' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Филимонов М.О., Блохин И.А.', (SELECT id FROM sport_ranks WHERE code = 'i')),
  (29, 'Захаров', 'Максим', 'Александрович', 2008, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МУ ДО «МЦРФКиС» Черепановского района' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Бутенко И.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (30, 'Ляукин', 'Кирилл', 'Сергеевич', 1999, 'm', (SELECT id FROM regions WHERE name = 'Республика Татарстан' AND country = 'RU'), (SELECT id FROM clubs WHERE name = '"УСЗ Импульс" г. Буинск' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Татарстан' AND country = 'RU')), 'Трофимов М.А., Низамова А.А., Турищев Д.В.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (31, 'Каргин', 'Сергей', 'Ярославович', 1998, 'm', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО «Онохойская СШ»' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')), 'Рассадин А.А., Каргин Я.Л., Леонов С.Т.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (32, 'Астахов', 'Евгений', 'Михайлович', 2002, 'm', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ГБУ ДО МКСШОР «Запад» Отделение «Семёрка»' AND region_id = (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')), 'Ландин А.Ю., Турищев Д.В., Ромашин Ю.А.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (33, 'Сарсембаев', 'Ильяс', 'Асхатович', 1999, 'm', (SELECT id FROM regions WHERE name = 'Ямало-Ненецкий автономный округ' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШ «Зенит»' AND region_id = (SELECT id FROM regions WHERE name = 'Ямало-Ненецкий автономный округ' AND country = 'RU')), 'Латыпов Е.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (34, 'Порцев', 'Роман', 'Геннадьевич', 1987, 'm', (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ ДО «СШ «Прикамье» г. Перми' AND region_id = (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU')), 'Мошев Д.И.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (35, 'Любимский', 'Сергей', 'Александрович', 1992, 'm', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ВС РФ' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')), 'Трофимов М.А., Леонов С.Т., Блохин И.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (36, 'Дубель', 'Алексей', 'Викторович', 1990, 'm', (SELECT id FROM regions WHERE name = 'Курганская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУДО "Варгашинская СШ"' AND region_id = (SELECT id FROM regions WHERE name = 'Курганская область' AND country = 'RU')), 'Стрекаловских С.К.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (37, 'Молчанов', 'Дианисий', 'Николаевич', 2005, 'm', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОРСВС им В.Ф. Краевского' AND region_id = (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')), 'Катаев И.В., Бирюков С.Н.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (38, 'Филиппов', 'Евгений', 'Борисович', 1995, 'm', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ВС РФ' AND region_id = (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')), 'Анасенко А.В.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (39, 'Баландин', 'Андрей', 'Александрович', 1996, 'm', (SELECT id FROM regions WHERE name = 'Курганская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУДО "Каргапольская ДЮСШ"' AND region_id = (SELECT id FROM regions WHERE name = 'Курганская область' AND country = 'RU')), 'Стрекаловских С.К.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (40, 'Пеньков', 'Ян', 'Евгеньевич', 2010, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МУ ДО "МЦРФКиС" Черепановского района' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Бутенко А.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (41, 'Согоян', 'Артём', 'Ражденович', 1988, 'm', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ «РУСС»' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Петров В.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (42, 'Иванов', 'Виталий', 'Викторович', 1978, 'm', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШОР «Югория» им. А.А. Пилояна' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Шпартко М.А., Шульга Н.В.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (43, 'Бородынкин', 'Олег', 'Александрович', 2002, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РО ООО "ВФГС" в Новосибирской области' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Баер П.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (44, 'Черкашин', 'Дмитрий', 'Андреевич', 1999, 'm', (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР Кристалл' AND region_id = (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU')), 'Тимофеев Н.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (45, 'Чуев', 'Павел', 'Владимирович', 1997, 'm', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского' AND region_id = (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')), 'Кириллов С.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (46, 'Самочернов', 'Иван', 'Николаевич', 1998, 'm', (SELECT id FROM regions WHERE name = 'Курганская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУДО "Каргапольская ДЮСШ"' AND region_id = (SELECT id FROM regions WHERE name = 'Курганская область' AND country = 'RU')), 'Стрекаловских С.К.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (47, 'Селиверстов', 'Семен', 'Васильевич', 1989, 'm', (SELECT id FROM regions WHERE name = 'Челябинская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'Олимп' AND region_id = (SELECT id FROM regions WHERE name = 'Челябинская область' AND country = 'RU')), 'Нестеренко Д.В., Ташланов И.С.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (48, 'Андрущенко', 'Сергей', 'Александрович', 2005, 'm', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ГБУ ДО МКСШОР «Запад» Отделение «Семёрка»' AND region_id = (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')), 'Ландин А.Ю., Ермаков К.И., Турищев Д.В.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (49, 'Полибин', 'Михаил', 'Леонидович', 2004, 'm', (SELECT id FROM regions WHERE name = 'Алтайский край' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'Федерация гиревого спорта Алтайского Края' AND region_id = (SELECT id FROM regions WHERE name = 'Алтайский край' AND country = 'RU')), 'Белова Н.Ю.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (50, 'Минуллин', 'Марсель', 'Ринатович', 2000, 'm', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ЦСП Омской области' AND region_id = (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')), 'Елисеев В.С., Гарифуллин Р.Ф., Лавринович Ю.Я.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (51, 'Акульшин', 'Алексей', 'Сергеевич', 1994, 'm', (SELECT id FROM regions WHERE name = 'Оренбургская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШ №1 им. Л.Д. Ковалевского' AND region_id = (SELECT id FROM regions WHERE name = 'Оренбургская область' AND country = 'RU')), 'Лавринов В.А.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (52, 'Рысник', 'Сергей', 'Михайлович', 1995, 'm', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'БУ ДО города Омска «СШОР №33»' AND region_id = (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')), 'Елисеев В.С., Переверзев Н.И.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (53, 'Кулаков', 'Иван', 'Иванович', 1998, 'm', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР «Маршал»' AND region_id = (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')), 'Шматов И.Б., Трофимов М.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (54, 'Кирюхин', 'Роман', 'Александрович', 1997, 'm', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ФГС КО' AND region_id = (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')), 'Соловьев А.В.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (55, 'Николаев', 'Аркадий', 'Анатольевич', 2002, 'm', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШОР «Югория» им. А.А. Пилояна' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Шпартко М.А., Рябков А.И.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (56, 'Черкашин', 'Иван', 'Андреевич', 1999, 'm', (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР' AND region_id = (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU')), 'Тимофеев Н.А., Черкашин Д.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (57, 'Захаров', 'Андрей', 'Валентинович', 1993, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РО ООО "ВФГС" в Новосибирской области' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Петухов А.В., Бутенко А.А.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (58, 'Кулик', 'Никита', 'Алексеевич', 2005, 'm', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ГБУ ДО МКСШОР «Запад» Отделение «Семёрка»' AND region_id = (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')), 'Ландин А.Ю., Турищев Д.В.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (59, 'Микряков', 'Михаил', 'Геннадьевич', 2007, 'm', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского' AND region_id = (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')), 'Катаев И.В., Федосеев А.В.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (60, 'Зуев', 'Илья', 'Александрович', 2007, 'm', (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ ДО «СШ «Прикамье» г. Перми' AND region_id = (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU')), 'Мошев Д.И., Ермаков И.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (61, 'Ефремов', 'Сергей', 'Евгеньевич', 1997, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РО ООО "ВФГС" в Новосибирской области' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Бутенко А.А.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (62, 'Дашкевич', 'Владимир', 'Олегович', 1984, 'm', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ «РУСС»' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Петров В.А., Шульга Н.В.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (63, 'Балабанов', 'Сергей', 'Андреевич', 1996, 'm', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ВС РФ' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')), 'Леонов С.Т., Гаденин А.Г., Трофимов М.А.', (SELECT id FROM sport_ranks WHERE code = 'zms')),
  (64, 'Шевелев', 'Дмитрий', 'Владимирович', 1989, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ВС РФ' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Рябченко А.В.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (65, 'Лебедев', 'Дмитрий', 'Николаевич', 2008, 'm', (SELECT id FROM regions WHERE name = 'Вологодская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР №3, г. Череповец' AND region_id = (SELECT id FROM regions WHERE name = 'Вологодская область' AND country = 'RU')), 'Шемякин О.Л.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (66, 'Симашкевич', 'Евгений', 'Валентинович', 1991, 'm', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ВС РФ' AND region_id = (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')), 'Анасенко А.В.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (67, 'Турищев', 'Дмитрий', 'Владимирович', 1992, 'm', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ГБУ ДО МКСШОР «Запад», отделение «Семёрка»' AND region_id = (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')), 'Ландин А.Ю., Винтовкин Н.В., Дуюнов Е.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (68, 'Калистратов', 'Артем', 'Валерьевич', 1992, 'm', (SELECT id FROM regions WHERE name = 'Смоленская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'КШС 1' AND region_id = (SELECT id FROM regions WHERE name = 'Смоленская область' AND country = 'RU')), 'Сергеев С.В.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (69, 'Станкович', 'Боян', NULL, 1988, 'm', (SELECT id FROM regions WHERE name = 'Ярославская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ФГС ЯО' AND region_id = (SELECT id FROM regions WHERE name = 'Ярославская область' AND country = 'RU')), 'Барков А.П., Егоров В.В.', (SELECT id FROM sport_ranks WHERE code = 'i')),
  (70, 'Новиков', 'Александр', 'Алексеевич', 1992, 'm', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ДЮСШ Краснозерского района' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Исионов В.Н., Сологубов К.В.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (71, 'Трофимова', 'Милена', 'Михайловна', 2007, 'f', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР «Маршал»' AND region_id = (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')), 'Пянко И.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (72, 'Прохорова', 'Ангелина', 'Вячеславовна', 2005, 'f', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МУ ДО "МЦРФКиС" Черепановского района' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Бутенко И.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (73, 'Васюкова', 'Регина', 'Александровна', 2010, 'f', (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МУ ДО «МЦРФКиС» Черепановского района' AND region_id = (SELECT id FROM regions WHERE name = 'Новосибирская область' AND country = 'RU')), 'Бутенко И.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (74, 'Ныныч', 'Маргарита', 'Анатольевна', 1996, 'f', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШ №3, г. Улан-Удэ' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')), 'Рассадин А.А., Трофимов М.А.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (75, 'Кошурникова', 'Валерия', 'Александровна', 2012, 'f', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШОР «Югория» им. А.А. Пилояна' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Шпартко М.А.', (SELECT id FROM sport_ranks WHERE code = 'i')),
  (76, 'Чернова', 'Кира', 'Николаевна', 2009, 'f', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР «Маршал»' AND region_id = (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')), 'Барбакова Н.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (77, 'Шилихина', 'Дарья', 'Павловна', 2006, 'f', (SELECT id FROM regions WHERE name = 'Смоленская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'КШС 1/ СГУС' AND region_id = (SELECT id FROM regions WHERE name = 'Смоленская область' AND country = 'RU')), 'Сергеев С.В., Бирюков С.Н., Иванов Е.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (78, 'Меденцева', 'Дарья', 'Александровна', 2004, 'f', (SELECT id FROM regions WHERE name = 'Кемеровская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ ДО "КСШ КМО"' AND region_id = (SELECT id FROM regions WHERE name = 'Кемеровская область' AND country = 'RU')), 'Шляхова Д.П.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (79, 'Пивень', 'Александра', 'Максимовна', 2004, 'f', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР «Маршал»' AND region_id = (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')), 'Пянко И.А.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (80, 'Мартынова', 'Любовь', 'Владимировна', 2007, 'f', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ГБУ ДО МКСШОР «Запад» Отделение «Семёрка»' AND region_id = (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')), 'Ландин А.Ю., Бирюков С.Н.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (81, 'Матвеева', 'Елена', 'Евгеньевна', 1974, 'f', (SELECT id FROM regions WHERE name = 'Кировская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'КОГАУ "СШОР "Юность "' AND region_id = (SELECT id FROM regions WHERE name = 'Кировская область' AND country = 'RU')), 'Малков Е.И.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (82, 'Подольская', 'Анастасия', 'Владимировна', 2005, 'f', (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РО ООО «ВФГС» в г. Москве' AND region_id = (SELECT id FROM regions WHERE name = 'г. Москва' AND country = 'RU')), 'Соловьев А.В.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (83, 'Рындина', 'Владислава', 'Романовна', 2009, 'f', (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ДОО(П)Ц "Юниор"' AND region_id = (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU')), 'Иванов Д.С.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (84, 'Григорьева', 'Эмилия', 'Сергеевна', 2006, 'f', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШ №3, г. Улан-Удэ' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')), 'Пивень А.М., Коломин Д.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (85, 'Воропаева', 'Виктория', 'Витальевна', 2004, 'f', (SELECT id FROM regions WHERE name = 'Воронежская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МКУ ДО "Бобровская СШ имени В.Л. Паткина"' AND region_id = (SELECT id FROM regions WHERE name = 'Воронежская область' AND country = 'RU')), 'Сорокин Н.Н.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (86, 'Кошурникова', 'Анастасия', 'Александровна', 2003, 'f', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШОР «Югория» им. А.А. Пилояна' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Шпартко М.А.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (87, 'Ермолина', 'Ирина', 'Евгеньевна', 2008, 'f', (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'Федерация гиревого спорта Томской области' AND region_id = (SELECT id FROM regions WHERE name = 'Томская область' AND country = 'RU')), 'Бажин А.М.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (88, 'Альянова', 'Виктория', 'Евгеньевна', 2004, 'f', (SELECT id FROM regions WHERE name = 'Брянская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШОР по борьбе' AND region_id = (SELECT id FROM regions WHERE name = 'Брянская область' AND country = 'RU')), 'Гомонов В.Н., Лукьянчиков Ю.В.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (89, 'Забелинская', 'Дарья', 'Александровна', 2003, 'f', (SELECT id FROM regions WHERE name = 'Архангельская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'САФУ Арктика' AND region_id = (SELECT id FROM regions WHERE name = 'Архангельская область' AND country = 'RU')), 'Коршун А.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (90, 'Ельчанинова', 'Вероника', 'Сергеевна', 2003, 'f', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'БУ ДО города Омска «СШОР №33»' AND region_id = (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')), 'Елисеева Н.А., Сагандыков К.К.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (91, 'Суменкова', 'Анастасия', 'Дмитриевна', 2009, 'f', (SELECT id FROM regions WHERE name = 'Смоленская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'КШС 1' AND region_id = (SELECT id FROM regions WHERE name = 'Смоленская область' AND country = 'RU')), 'Власенкова Т.И.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (92, 'Мартынова', 'Ирина', 'Александровна', 1999, 'f', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР «Маршал»' AND region_id = (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')), 'Трофимов М.А.', (SELECT id FROM sport_ranks WHERE code = 'zms')),
  (93, 'Полякова', 'Полина', 'Сергеевна', 1999, 'f', (SELECT id FROM regions WHERE name = 'Тюменская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ТРО ООО «ВФГС»' AND region_id = (SELECT id FROM regions WHERE name = 'Тюменская область' AND country = 'RU')), 'Мартьянов А.В., Барков А.П., Садыков Р.И.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (94, 'Вяткина', 'Вера', 'Павловна', 1999, 'f', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РО ООО «ВФГС» в Омской области' AND region_id = (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')), 'Сагандыков К.К.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (95, 'Попова', 'Мария', 'Алексеевна', 2005, 'f', (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ССК «КИТ на спорте"' AND region_id = (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU')), 'Паклин П.А.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (96, 'Филимонова', 'Карина', 'Денисовна', 2006, 'f', (SELECT id FROM regions WHERE name = 'Кировская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'КОГАУ «СШОР «Юность»' AND region_id = (SELECT id FROM regions WHERE name = 'Кировская область' AND country = 'RU')), 'Малков Е.И.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (97, 'Побережная', 'Анна', 'Владимировна', 2010, 'f', (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СШОР «Маршал»' AND region_id = (SELECT id FROM regions WHERE name = 'Калужская область' AND country = 'RU')), 'Пянко И.А.', (SELECT id FROM sport_ranks WHERE code = 'i')),
  (98, 'Врубель', 'Дарья', 'Васильевна', 2000, 'f', (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'БУ ДО города Омска «СШОР №33»' AND region_id = (SELECT id FROM regions WHERE name = 'Омская область' AND country = 'RU')), 'Сагандыков К.К., Переверзев Н.И.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (99, 'Баранова', 'Дарья', 'Андреевна', 2008, 'f', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ ДО «Спортивная школа»' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Рябоконь О.Н.', (SELECT id FROM sport_ranks WHERE code = 'i')),
  (100, 'Махкамова', 'Парвина', 'Маруфовна', 2007, 'f', (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ ДО «СШ «Прикамье» г. Перми' AND region_id = (SELECT id FROM regions WHERE name = 'Пермский край' AND country = 'RU')), 'Мошев Д.И.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (101, 'Бенидзе', 'Джони', 'Бадриевич', 1990, 'm', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского' AND region_id = (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')), 'Кириллов С.А., Огарев В.Я., Старовойтов А.Л.', (SELECT id FROM sport_ranks WHERE code = 'zms')),
  (102, 'Кузнецов', 'Роман', 'Андреевич', 2009, 'm', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШ №3, г. Улан-Удэ' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')), 'Коломин Д.А., Алексеев В.И.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (103, 'Манаков', 'Трофим', 'Анатольевич', 2000, 'm', (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ ДО «СШ №2» Сургутского района' AND region_id = (SELECT id FROM regions WHERE name = 'Ханты-Мансийский АО - Югра' AND country = 'RU')), 'Трофимова А.А., Садыков Р.И., Дементьев А.Ф.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (104, 'Кашкаров', 'Артур', 'Анатольевич', 2005, 'm', (SELECT id FROM regions WHERE name = 'Алтайский край' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'спортивный клуб "АГАУ"' AND region_id = (SELECT id FROM regions WHERE name = 'Алтайский край' AND country = 'RU')), 'Платонов С.С.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (105, 'Митюкевич', 'Станислав', 'Николаевич', 2008, 'm', (SELECT id FROM regions WHERE name = 'Республика Башкортостан' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МАУ ДО СШОР' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Башкортостан' AND country = 'RU')), 'Гладких В.Л.', (SELECT id FROM sport_ranks WHERE code = 'i')),
  (106, 'Клявлин', 'Андрей', 'Викторович', 2006, 'm', (SELECT id FROM regions WHERE name = 'Челябинская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'РО ООО ВФГС в Челябинской области' AND region_id = (SELECT id FROM regions WHERE name = 'Челябинская область' AND country = 'RU')), 'Симушин А.М., Дедюхин И.В.', (SELECT id FROM sport_ranks WHERE code = 'kms')),
  (107, 'Зуев', 'Владислав', 'Алексеевич', 2000, 'm', (SELECT id FROM regions WHERE name = 'Воронежская область' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ВС РФ' AND region_id = (SELECT id FROM regions WHERE name = 'Воронежская область' AND country = 'RU')), 'Колесниченко Н.А.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (108, 'Узюкин', 'Анатолий', 'Эдуардович', 2000, 'm', (SELECT id FROM regions WHERE name = 'Чувашская Республика' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ФСК "Улап", СШ Энергия' AND region_id = (SELECT id FROM regions WHERE name = 'Чувашская Республика' AND country = 'RU')), 'Глинкин Б.Н.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (109, 'Василевич', 'Добрыня', 'Андреевич', 2000, 'm', (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'МБУ ДО СШ №3, г. Улан-Удэ' AND region_id = (SELECT id FROM regions WHERE name = 'Республика Бурятия' AND country = 'RU')), 'Рассадин А.А., Сабадажев В.В.', (SELECT id FROM sport_ranks WHERE code = 'ms')),
  (110, 'Щербин', 'Олег', 'Владимирович', 1989, 'm', (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского' AND region_id = (SELECT id FROM regions WHERE name = 'г. Санкт-Петербург' AND country = 'RU')), 'Никифоров А.В.', (SELECT id FROM sport_ranks WHERE code = 'msmk')),
  (111, 'Аникушко', 'Семён', 'Сергеевич', 2009, 'm', (SELECT id FROM regions WHERE name = 'Алтайский край' AND country = 'RU'), (SELECT id FROM clubs WHERE name = 'ДЮСШ Кулундинского района' AND region_id = (SELECT id FROM regions WHERE name = 'Алтайский край' AND country = 'RU')), 'Катаев И.Н.', (SELECT id FROM sport_ranks WHERE code = 'i'));

INSERT INTO athlete_slugs (slug, athlete_id) VALUES
  ('butenko-evgeniy-1995', 1),
  ('sirazetdinov-danil-2007', 2),
  ('yakushev-roman-2002', 3),
  ('rudnev-ruslan-1994', 4),
  ('nedorezov-vasiliy-1992', 5),
  ('zhbanov-aleksey-1986', 6),
  ('kormilicyn-ivan-2010', 7),
  ('zhalov-yaroslav-2007', 8),
  ('filatov-aleksey-2008', 9),
  ('morozovich-vladislav-1999', 10),
  ('ryzhkov-anton-1994', 11),
  ('zaharov-kirill-2007', 12),
  ('kolomin-dmitriy-1999', 13),
  ('hamidov-fahriddin-2002', 14),
  ('sergeev-aleksey-2001', 15),
  ('rybskiy-pavel-2008', 16),
  ('melyuhin-kirill-2011', 17),
  ('sidorenkov-aleksandr-2010', 18),
  ('belyaev-ivan-1992', 19),
  ('ryabkov-aleksey-1993', 20),
  ('bagrov-maksim-2009', 21),
  ('fomin-fedor-2004', 22),
  ('trofimov-timur-2011', 23),
  ('novoselov-andrey-2004', 24),
  ('semenov-nikita-1993', 25),
  ('rozhin-egor-1987', 26),
  ('zhibinov-fedor-2004', 27),
  ('kolokolov-nikita-2007', 28),
  ('zaharov-maksim-2008', 29),
  ('lyaukin-kirill-1999', 30),
  ('kargin-sergey-1998', 31),
  ('astahov-evgeniy-2002', 32),
  ('sarsembaev-ilyas-1999', 33),
  ('porcev-roman-1987', 34),
  ('lyubimskiy-sergey-1992', 35),
  ('dubel-aleksey-1990', 36),
  ('molchanov-dianisiy-2005', 37),
  ('filippov-evgeniy-1995', 38),
  ('balandin-andrey-1996', 39),
  ('penkov-yan-2010', 40),
  ('sogoyan-artem-1988', 41),
  ('ivanov-vitaliy-1978', 42),
  ('borodynkin-oleg-2002', 43),
  ('cherkashin-dmitriy-1999', 44),
  ('chuev-pavel-1997', 45),
  ('samochernov-ivan-1998', 46),
  ('seliverstov-semen-1989', 47),
  ('andruschenko-sergey-2005', 48),
  ('polibin-mihail-2004', 49),
  ('minullin-marsel-2000', 50),
  ('akulshin-aleksey-1994', 51),
  ('rysnik-sergey-1995', 52),
  ('kulakov-ivan-1998', 53),
  ('kiryuhin-roman-1997', 54),
  ('nikolaev-arkadiy-2002', 55),
  ('cherkashin-ivan-1999', 56),
  ('zaharov-andrey-1993', 57),
  ('kulik-nikita-2005', 58),
  ('mikryakov-mihail-2007', 59),
  ('zuev-ilya-2007', 60),
  ('efremov-sergey-1997', 61),
  ('dashkevich-vladimir-1984', 62),
  ('balabanov-sergey-1996', 63),
  ('shevelev-dmitriy-1989', 64),
  ('lebedev-dmitriy-2008', 65),
  ('simashkevich-evgeniy-1991', 66),
  ('turischev-dmitriy-1992', 67),
  ('kalistratov-artem-1992', 68),
  ('stankovich-boyan-1988', 69),
  ('novikov-aleksandr-1992', 70),
  ('trofimova-milena-2007', 71),
  ('prohorova-angelina-2005', 72),
  ('vasyukova-regina-2010', 73),
  ('nynych-margarita-1996', 74),
  ('koshurnikova-valeriya-2012', 75),
  ('chernova-kira-2009', 76),
  ('shilihina-darya-2006', 77),
  ('medenceva-darya-2004', 78),
  ('piven-aleksandra-2004', 79),
  ('martynova-lyubov-2007', 80),
  ('matveeva-elena-1974', 81),
  ('podolskaya-anastasiya-2005', 82),
  ('ryndina-vladislava-2009', 83),
  ('grigoreva-emiliya-2006', 84),
  ('voropaeva-viktoriya-2004', 85),
  ('koshurnikova-anastasiya-2003', 86),
  ('ermolina-irina-2008', 87),
  ('alyanova-viktoriya-2004', 88),
  ('zabelinskaya-darya-2003', 89),
  ('elchaninova-veronika-2003', 90),
  ('sumenkova-anastasiya-2009', 91),
  ('martynova-irina-1999', 92),
  ('polyakova-polina-1999', 93),
  ('vyatkina-vera-1999', 94),
  ('popova-mariya-2005', 95),
  ('filimonova-karina-2006', 96),
  ('poberezhnaya-anna-2010', 97),
  ('vrubel-darya-2000', 98),
  ('baranova-darya-2008', 99),
  ('mahkamova-parvina-2007', 100),
  ('benidze-dzhoni-1990', 101),
  ('kuznecov-roman-2009', 102),
  ('manakov-trofim-2000', 103),
  ('kashkarov-artur-2005', 104),
  ('mityukevich-stanislav-2008', 105),
  ('klyavlin-andrey-2006', 106),
  ('zuev-vladislav-2000', 107),
  ('uzyukin-anatoliy-2000', 108),
  ('vasilevich-dobrynya-2000', 109),
  ('scherbin-oleg-1989', 110),
  ('anikushko-semen-2009', 111);

INSERT INTO results (id, category_id, athlete_id, place, total_reps, points, body_weight_kg, rank_achieved_id, discipline_id, bell_kg, hands, time_limit_min, competition_id, event_date, raw_name, raw_club, raw_region, protocol_id, source_page) VALUES
  (1, 1, 1, 1, 81, NULL, 62.65, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Бутенко Евгений Александрович', 'ГАУ НСО «РЦСП СК и СР»', 'Новосибирская область', 1, 2),
  (2, 1, 2, 2, 61, NULL, 62.05, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Сиразетдинов Данил Ильфатович', 'МАУ ДО «СШ «Прикамье» г. Перми', 'Пермский край', 1, 2),
  (3, 1, 3, 3, 56, NULL, 62.7, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Якушев Роман Владимирович', 'ВС РФ', 'Республика Бурятия', 1, 2),
  (4, 1, 4, 4, 55, NULL, 62.3, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Руднев Руслан Сергеевич', 'РОО ФГС г. САНКТ ПЕТЕРБУРГ', 'г. Санкт-Петербург', 1, 2),
  (5, 1, 5, 5, 54, NULL, 62.8, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Недорезов Василий Сергеевич', 'МБУ ДО «Онохойская СШ»', 'Республика Бурятия', 1, 2),
  (6, 1, 6, 6, 52, NULL, 62.95, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Жбанов Алексей Александрович', 'СДСШОР им. Краевского', 'г. Санкт-Петербург', 1, 2),
  (7, 1, 7, 7, 44, NULL, 62.75, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Кормилицын Иван Николаевич', 'СШОР «Маршал»', 'Калужская область', 1, 2),
  (8, 1, 8, 8, 38, NULL, 61.7, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Жалов Ярослав Борисович', 'МБУ ДО СШОР «Югория» им. А.А. Пилояна', 'Ханты-Мансийский АО - Югра', 1, 2),
  (9, 1, 9, 9, 11, NULL, 61.6, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Филатов Алексей Александрович', 'МУ ДО «МЦРФКиС» Черепановского района', 'Новосибирская область', 1, 2),
  (10, 2, 10, 1, 73, NULL, 67.9, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Морозович Владислав Павлович', 'РЦСП', 'Омская область', 1, 3),
  (11, 2, 11, 2, 70, NULL, 67.75, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Рыжков Антон Николаевич', 'СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского', 'г. Санкт-Петербург', 1, 3),
  (12, 2, 12, 3, 67, NULL, 67.5, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Захаров Кирилл Дмитриевич', 'МУ ДО «МЦРФКиС» Черепановского района', 'Новосибирская область', 1, 3),
  (13, 2, 13, 4, 67, NULL, 67.7, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Коломин Дмитрий Андреевич', 'МБУ ДО «Онохойская СШ»', 'Республика Бурятия', 1, 3),
  (14, 2, 14, 5, 61, NULL, 67.6, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Хамидов Фахриддин Фарход угли', 'СШОР «Маршал»', 'Калужская область', 1, 3),
  (15, 2, 15, 6, 58, NULL, 67.85, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Сергеев Алексей Вячеславович', 'МАУ ДО «СШ №2» Сургутского района', 'Ханты-Мансийский АО - Югра', 1, 3),
  (16, 2, 16, 7, 56, NULL, 68.0, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Рыбский Павел Сергеевич', 'Спортивная школа №1 в Асино', 'Томская область', 1, 3),
  (17, 2, 17, 8, 45, NULL, 67.6, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Мелюхин Кирилл Александрович', 'МБУ ДО «ДЮСШ «Спарт»', 'Пермский край', 1, 3),
  (18, 2, 18, 9, 42, NULL, 67.5, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Сидоренков Александр Александрович', 'РО ООО ВФГС в г. Москве', 'г. Москва', 1, 3),
  (19, 3, 19, 1, 79, NULL, 71.05, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Беляев Иван Сергеевич', 'МБУ ДО СШОР «Югория» им. А.А. Пилояна', 'Ханты-Мансийский АО - Югра', 1, 4),
  (20, 3, 20, 2, 78, NULL, 71.85, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Рябков Алексей Игоревич', 'МБУ ДО СШОР «Югория» им. А.А. Пилояна', 'Ханты-Мансийский АО - Югра', 1, 4),
  (21, 3, 21, 3, 71, NULL, 72.0, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Багров Максим Дмитриевич', 'РО ООО "ВФГС" в г. Москве', 'г. Москва', 1, 4),
  (22, 3, 22, 4, 69, NULL, 72.1, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Фомин Фёдор Алексеевич', 'МБУ ДО СШОР 5 г Белгород', 'Белгородская область', 1, 4),
  (23, 3, 23, 5, 66, NULL, 72.85, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Трофимов Тимур Михайлович', 'СШОР Маршал', 'Калужская область', 1, 4),
  (24, 3, 24, 6, 65, NULL, 72.3, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Новоселов Андрей Евгеньевич', 'КОГАУ "СШОР "Юность"', 'Кировская область', 1, 4),
  (25, 3, 25, 7, 51, NULL, 72.85, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Семенов Никита Андреевич', 'РО ООО «ВФГС» в Челябинской области', 'Челябинская область', 1, 4),
  (26, 3, 26, 8, 46, NULL, 72.55, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Рожин Егор Иннокентьевич', 'Республиканский центр национальных видов спорта', 'Республика Саха (Якутия)', 1, 4),
  (27, 3, 27, 9, 44, NULL, 72.15, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Жибинов Фёдор Васильевич', 'Спортивная школа г. Черногорск', 'Республика Хакасия', 1, 4),
  (28, 3, 28, 10, 34, NULL, 72.5, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Колоколов Никита Александрович', 'НГТУ', 'Новосибирская область', 1, 4),
  (29, 3, 29, 11, 31, NULL, 72.65, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Захаров Максим Александрович', 'МУ ДО «МЦРФКиС» Черепановского района', 'Новосибирская область', 1, 4),
  (30, 4, 30, 1, 81, NULL, 77.4, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Ляукин Кирилл Сергеевич', '"УСЗ Импульс" г. Буинск', 'Республика Татарстан', 1, 5),
  (31, 4, 31, 2, 79, NULL, 76.95, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Каргин Сергей Ярославович', 'МБУ ДО «Онохойская СШ»', 'Республика Бурятия', 1, 5),
  (32, 4, 32, 3, 79, NULL, 77.45, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Астахов Евгений Михайлович', 'ГБУ ДО МКСШОР «Запад» Отделение «Семёрка»', 'г. Москва', 1, 5),
  (33, 4, 33, 4, 78, NULL, 77.25, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Сарсембаев Ильяс Асхатович', 'МБУ ДО СШ «Зенит»', 'Ямало-Ненецкий автономный округ', 1, 5),
  (34, 4, 34, 5, 67, NULL, 77.65, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Порцев Роман Геннадьевич', 'МАУ ДО «СШ «Прикамье» г. Перми', 'Пермский край', 1, 5),
  (35, 4, 35, 6, 67, NULL, 77.95, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Любимский Сергей Александрович', 'ВС РФ', 'Республика Бурятия', 1, 5),
  (36, 4, 36, 7, 65, NULL, 77.75, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Дубель Алексей Викторович', 'МБУДО "Варгашинская СШ"', 'Курганская область', 1, 5),
  (37, 4, 37, 8, 65, NULL, 77.95, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Молчанов Дианисий Николаевич', 'СШОРСВС им В.Ф. Краевского', 'г. Санкт-Петербург', 1, 5),
  (38, 4, 38, 9, 61, NULL, 78.0, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Филиппов Евгений Борисович', 'ВС РФ', 'Омская область', 1, 5),
  (39, 4, 39, 10, 54, NULL, 77.85, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Баландин Андрей Александрович', 'МБУДО "Каргапольская ДЮСШ"', 'Курганская область', 1, 5),
  (40, 4, 40, 11, 48, NULL, 74.7, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Пеньков Ян Евгеньевич', 'МУ ДО "МЦРФКиС" Черепановского района', 'Новосибирская область', 1, 5),
  (41, 4, 41, 12, 47, NULL, 77.85, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Согоян Артём Ражденович', 'МАУ «РУСС»', 'Ханты-Мансийский АО - Югра', 1, 5),
  (42, 4, 42, 13, 47, NULL, 78.0, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Иванов Виталий Викторович', 'МБУ ДО СШОР «Югория» им. А.А. Пилояна', 'Ханты-Мансийский АО - Югра', 1, 5),
  (43, 5, 43, 1, 91, NULL, 84.75, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Бородынкин Олег Александрович', 'РО ООО "ВФГС" в Новосибирской области', 'Новосибирская область', 1, 6),
  (44, 5, 44, 2, 85, NULL, 84.05, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Черкашин Дмитрий Андреевич', 'СШОР Кристалл', 'Томская область', 1, 6),
  (45, 5, 45, 3, 83, NULL, 83.4, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Чуев Павел Владимирович', 'СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского', 'г. Санкт-Петербург', 1, 6),
  (46, 5, 46, 4, 81, NULL, 84.5, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Самочернов Иван Николаевич', 'МБУДО "Каргапольская ДЮСШ"', 'Курганская область', 1, 6),
  (47, 5, 47, 5, 78, NULL, 83.9, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Селиверстов Семен Васильевич', 'Олимп', 'Челябинская область', 1, 6),
  (48, 5, 48, 6, 76, NULL, 84.15, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Андрущенко Сергей Александрович', 'ГБУ ДО МКСШОР «Запад» Отделение «Семёрка»', 'г. Москва', 1, 6),
  (49, 5, 49, 7, 69, NULL, 83.85, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Полибин Михаил Леонидович', 'Федерация гиревого спорта Алтайского Края', 'Алтайский край', 1, 6),
  (50, 5, 50, 8, 64, NULL, 83.55, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Минуллин Марсель Ринатович', 'ЦСП Омской области', 'Омская область', 1, 6),
  (51, 5, 51, 9, 57, NULL, 84.8, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Акульшин Алексей Сергеевич', 'СШ №1 им. Л.Д. Ковалевского', 'Оренбургская область', 1, 6),
  (52, 5, 52, 10, 56, NULL, 85.0, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Рысник Сергей Михайлович', 'БУ ДО города Омска «СШОР №33»', 'Омская область', 1, 6),
  (53, 6, 53, 1, 99, NULL, 94.9, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Кулаков Иван Иванович', 'СШОР «Маршал»', 'Калужская область', 1, 7),
  (54, 6, 54, 2, 82, NULL, 89.1, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Кирюхин Роман Александрович', 'ФГС КО', 'Калужская область', 1, 7),
  (55, 6, 55, 3, 81, NULL, 88.45, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Николаев Аркадий Анатольевич', 'МБУ ДО СШОР «Югория» им. А.А. Пилояна', 'Ханты-Мансийский АО - Югра', 1, 7),
  (56, 6, 56, 4, 75, NULL, 91.2, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Черкашин Иван Андреевич', 'СШОР', 'Томская область', 1, 7),
  (57, 6, 57, 5, 64, NULL, 93.2, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Захаров Андрей Валентинович', 'РО ООО "ВФГС" в Новосибирской области', 'Новосибирская область', 1, 7),
  (58, 6, 58, 6, 59, NULL, 92.3, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Кулик Никита Алексеевич', 'ГБУ ДО МКСШОР «Запад» Отделение «Семёрка»', 'г. Москва', 1, 7),
  (59, 6, 59, 7, 58, NULL, 93.75, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Микряков Михаил Геннадьевич', 'СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского', 'г. Санкт-Петербург, Самарская область', 1, 7),
  (60, 6, 60, 8, 52, NULL, 94.9, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Зуев Илья Александрович', 'МАУ ДО «СШ «Прикамье» г. Перми', 'Пермский край', 1, 7),
  (61, 6, 61, 9, 50, NULL, 90.8, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Ефремов Сергей Евгеньевич', 'РО ООО "ВФГС" в Новосибирской области', 'Новосибирская область', 1, 7),
  (62, 6, 62, 10, 40, NULL, 89.05, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Дашкевич Владимир Олегович', 'МАУ «РУСС»', 'Ханты-Мансийский АО - Югра', 1, 7),
  (63, 7, 63, 1, 95, NULL, 104.65, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Балабанов Сергей Андреевич', 'ВС РФ', 'Республика Бурятия', 1, 8),
  (64, 7, 64, 2, 94, NULL, 115.15, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Шевелев Дмитрий Владимирович', 'ВС РФ', 'Новосибирская область', 1, 8),
  (65, 7, 65, 3, 92, NULL, 95.1, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Лебедев Дмитрий Николаевич', 'СШОР №3, г. Череповец', 'Вологодская область', 1, 8),
  (66, 7, 66, 4, 89, NULL, 113.7, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Симашкевич Евгений Валентинович', 'ВС РФ', 'Омская область', 1, 8),
  (67, 7, 67, 5, 82, NULL, 99.4, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Турищев Дмитрий Владимирович', 'ГБУ ДО МКСШОР «Запад», отделение «Семёрка»', 'г. Москва', 1, 8),
  (68, 7, 68, 6, 63, NULL, 111.05, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Калистратов Артем Валерьевич', 'КШС 1', 'Смоленская область', 1, 8),
  (69, 7, 69, 7, 46, NULL, 103.95, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Станкович Боян', 'ФГС ЯО', 'Ярославская область', 1, 8),
  (70, 7, 70, 8, 35, NULL, 96.7, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 32, 'two', 10, 1, '2026-06-02', 'Новиков Александр Алексеевич', 'ДЮСШ Краснозерского района', 'Новосибирская область', 1, 8),
  (71, 8, 71, 1, 63, NULL, 57.95, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Трофимова Милена Михайловна', 'СШОР «Маршал»', 'Калужская область', 1, 9),
  (72, 8, 72, 2, 50, NULL, 56.35, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Прохорова Ангелина Вячеславовна', 'МУ ДО "МЦРФКиС" Черепановского района', 'Новосибирская область', 1, 9),
  (73, 8, 73, 3, 40, NULL, 53.35, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Васюкова Регина Александровна', 'МУ ДО «МЦРФКиС» Черепановского района', 'Новосибирская область', 1, 9),
  (74, 8, 74, 4, 39, NULL, 57.7, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Ныныч Маргарита Анатольевна', 'МБУ ДО СШ №3, г. Улан-Удэ', 'Республика Бурятия', 1, 9),
  (75, 8, 75, 5, 30, NULL, 54.75, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Кошурникова Валерия Александровна', 'МБУ ДО СШОР «Югория» им. А.А. Пилояна', 'Ханты-Мансийский АО - Югра', 1, 9),
  (76, 8, 76, 6, 28, NULL, 56.4, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Чернова Кира Николаевна', 'СШОР «Маршал»', 'Калужская область', 1, 9),
  (77, 8, 77, 7, 28, NULL, 57.45, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Шилихина Дарья Павловна', 'КШС 1/ СГУС', 'Смоленская область', 1, 9),
  (78, 8, 78, 8, 7, NULL, 57.25, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Меденцева Дарья Александровна', 'МАУ ДО "КСШ КМО"', 'Кемеровская область', 1, 9),
  (79, 9, 79, 1, 73, NULL, 60.3, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Пивень Александра Максимовна', 'СШОР «Маршал»', 'Калужская область', 1, 10),
  (80, 9, 80, 2, 50, NULL, 62.7, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Мартынова Любовь Владимировна', 'ГБУ ДО МКСШОР «Запад» Отделение «Семёрка»', 'г. Москва', 1, 10),
  (81, 9, 81, 3, 49, NULL, 61.5, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Матвеева Елена Евгеньевна', 'КОГАУ "СШОР "Юность "', 'Кировская область', 1, 10),
  (82, 9, 82, 4, 47, NULL, 59.1, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Подольская Анастасия Владимировна', 'РО ООО «ВФГС» в г. Москве', 'г. Москва', 1, 10),
  (83, 9, 83, 5, 39, NULL, 61.6, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Рындина Владислава Романовна', 'ДОО(П)Ц "Юниор"', 'Томская область', 1, 10),
  (84, 9, 84, 6, 30, NULL, 61.2, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Григорьева Эмилия Сергеевна', 'МБУ ДО СШ №3, г. Улан-Удэ', 'Республика Бурятия', 1, 10),
  (85, 10, 85, 1, 71, NULL, 65.75, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Воропаева Виктория Витальевна', 'МКУ ДО "Бобровская СШ имени В.Л. Паткина"', 'Воронежская область', 1, 11),
  (86, 10, 86, 2, 62, NULL, 63.05, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Кошурникова Анастасия Александровна', 'МБУ ДО СШОР «Югория» им. А.А. Пилояна', 'Ханты-Мансийский АО - Югра', 1, 11),
  (87, 10, 87, 3, 58, NULL, 64.9, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Ермолина Ирина Евгеньевна', 'Федерация гиревого спорта Томской области', 'Томская область', 1, 11),
  (88, 10, 88, 4, 38, NULL, 67.45, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Альянова Виктория Евгеньевна', 'МБУ ДО СШОР по борьбе', 'Брянская область', 1, 11),
  (89, 10, 89, 5, 28, NULL, 66.45, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Забелинская Дарья Александровна', 'САФУ Арктика', 'Архангельская область', 1, 11),
  (90, 10, 90, 6, 27, NULL, 67.9, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Ельчанинова Вероника Сергеевна', 'БУ ДО города Омска «СШОР №33»', 'Омская область', 1, 11),
  (91, 10, 91, 7, 26, NULL, 64.2, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Суменкова Анастасия Дмитриевна', 'КШС 1', 'Смоленская область', 1, 11),
  (92, 11, 92, 1, 85, NULL, 88.4, (SELECT id FROM sport_ranks WHERE code = 'msmk'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Мартынова Ирина Александровна', 'СШОР «Маршал»', 'Калужская область', 1, 12),
  (93, 11, 93, 2, 70, NULL, 88.85, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Полякова Полина Сергеевна', 'ТРО ООО «ВФГС»', 'Тюменская область', 1, 12),
  (94, 11, 94, 3, 61, NULL, 126.5, (SELECT id FROM sport_ranks WHERE code = 'ms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Вяткина Вера Павловна', 'РО ООО «ВФГС» в Омской области', 'Омская область', 1, 12),
  (95, 11, 95, 4, 53, NULL, 80.5, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Попова Мария Алексеевна', 'ССК «КИТ на спорте"', 'Пермский край', 1, 12),
  (96, 11, 96, 5, 53, NULL, 84.95, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Филимонова Карина Денисовна', 'КОГАУ «СШОР «Юность»', 'Кировская область', 1, 12),
  (97, 11, 97, 6, 47, NULL, 77.85, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Побережная Анна Владимировна', 'СШОР «Маршал»', 'Калужская область', 1, 12),
  (98, 11, 98, 7, 46, NULL, 100.4, (SELECT id FROM sport_ranks WHERE code = 'kms'), (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Врубель Дарья Васильевна', 'БУ ДО города Омска «СШОР №33»', 'Омская область', 1, 12),
  (99, 11, 99, 8, 30, NULL, 68.15, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Баранова Дарья Андреевна', 'МАУ ДО «Спортивная школа»', 'Ханты-Мансийский АО - Югра', 1, 12),
  (100, 11, 100, 9, 20, NULL, 88.1, NULL, (SELECT id FROM disciplines WHERE code = 'long_cycle'), 24, 'two', 10, 1, '2026-06-02', 'Махкамова Парвина Маруфовна', 'МАУ ДО «СШ «Прикамье» г. Перми', 'Пермский край', 1, 12),
  (101, 12, 101, 1, 142, NULL, 62.8, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Бенидзе Джони Бадриевич', 'СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского', 'г. Санкт-Петербург', 1, NULL),
  (102, 12, 1, 2, 140, NULL, 62.4, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Бутенко Евгений Александрович', 'ГАУ НСО «РЦСП СК и СР»', 'Новосибирская область', 1, NULL),
  (103, 12, 2, 3, 102, NULL, 62.3, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Сиразетдинов Данил Ильфатович', 'МАУ ДО «СШ «Прикамье» г. Перми', 'Пермский край', 1, NULL),
  (104, 12, 102, 4, 72, NULL, 62.85, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Кузнецов Роман Андреевич', 'МБУ ДО СШ №3, г. Улан-Удэ', 'Республика Бурятия', 1, NULL),
  (105, 12, 103, 5, 70, NULL, 62.9, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Манаков Трофим Анатольевич', 'МАУ ДО «СШ №2» Сургутского района', 'Ханты-Мансийский АО - Югра', 1, NULL),
  (106, 12, 7, 6, 65, NULL, 62.75, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Кормилицын Иван Николаевич', 'СШОР «Маршал»', 'Калужская область', 1, NULL),
  (107, 12, 104, 7, 62, NULL, 62.9, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Кашкаров Артур Анатольевич', 'спортивный клуб "АГАУ"', 'Алтайский край', 1, NULL),
  (108, 12, 8, 8, 60, NULL, 61.85, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Жалов Ярослав Борисович', 'МБУ ДО СШОР «Югория» им. А.А. Пилояна', 'Ханты-Мансийский АО - Югра', 1, NULL),
  (109, 12, 105, 9, 51, NULL, 61.65, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Митюкевич Станислав Николаевич', 'МАУ ДО СШОР', 'Республика Башкортостан', 1, NULL),
  (110, 12, 106, 10, 27, NULL, 62.7, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Клявлин Андрей Викторович', 'РО ООО ВФГС в Челябинской области', 'Челябинская область', 1, NULL),
  (111, 12, 9, 11, 10, NULL, 62.05, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Филатов Алексей Александрович', 'МУ ДО «МЦРФКиС» Черепановского района', 'Новосибирская область', 1, NULL),
  (112, 13, 107, 1, 136, NULL, 68.0, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Зуев Владислав Алексеевич', 'ВС РФ', 'Воронежская область', 1, NULL),
  (113, 13, 108, 2, 115, NULL, 67.3, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Узюкин Анатолий Эдуардович', 'ФСК "Улап", СШ Энергия', 'Чувашская Республика', 1, NULL),
  (114, 13, 109, 3, 111, NULL, 67.5, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Василевич Добрыня Андреевич', 'МБУ ДО СШ №3, г. Улан-Удэ', 'Республика Бурятия', 1, NULL),
  (115, 13, 12, 4, 111, NULL, 67.75, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Захаров Кирилл Дмитриевич', 'МУ ДО «МЦРФКиС» Черепановского района', 'Новосибирская область', 1, NULL),
  (116, 13, 110, 5, 109, NULL, 67.75, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Щербин Олег Владимирович', 'СПБ ГБУ ДО СШОРСВС им. В.Ф. Краевского', 'г. Санкт-Петербург', 1, NULL),
  (117, 13, 13, 6, 100, NULL, 67.85, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Коломин Дмитрий Андреевич', 'МБУ ДО «Онохойская СШ»', 'Республика Бурятия', 1, NULL),
  (118, 13, 14, 7, 100, NULL, 67.9, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Хамидов Фахриддин Фарход угли', 'СШОР «Маршал»', 'Калужская область', 1, NULL),
  (119, 13, 111, 8, 68, NULL, 67.2, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Аникушко Семён Сергеевич', 'ДЮСШ Кулундинского района', 'Алтайский край', 1, NULL),
  (120, 13, 16, 9, 65, NULL, 68.0, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Рыбский Павел Сергеевич', 'Спортивная школа №1 в Асино', 'Томская область', 1, NULL),
  (121, 13, 17, 10, 62, NULL, 66.75, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Мелюхин Кирилл Александрович', 'МБУ ДО «ДЮСШ «Спарт»', 'Пермский край', 1, NULL),
  (122, 13, 18, 11, 52, NULL, 67.35, NULL, (SELECT id FROM disciplines WHERE code = 'jerk'), 32, 'two', 10, 1, '2026-06-02', 'Сидоренков Александр Александрович', 'РО ООО ВФГС в г. Москве', 'г. Москва', 1, NULL);

INSERT INTO result_reps (id, result_id, exercise, hand, reps) VALUES
  (1, 1, 'long_cycle', 'both', 81),
  (2, 2, 'long_cycle', 'both', 61),
  (3, 3, 'long_cycle', 'both', 56),
  (4, 4, 'long_cycle', 'both', 55),
  (5, 5, 'long_cycle', 'both', 54),
  (6, 6, 'long_cycle', 'both', 52),
  (7, 7, 'long_cycle', 'both', 44),
  (8, 8, 'long_cycle', 'both', 38),
  (9, 9, 'long_cycle', 'both', 11),
  (10, 10, 'long_cycle', 'both', 73),
  (11, 11, 'long_cycle', 'both', 70),
  (12, 12, 'long_cycle', 'both', 67),
  (13, 13, 'long_cycle', 'both', 67),
  (14, 14, 'long_cycle', 'both', 61),
  (15, 15, 'long_cycle', 'both', 58),
  (16, 16, 'long_cycle', 'both', 56),
  (17, 17, 'long_cycle', 'both', 45),
  (18, 18, 'long_cycle', 'both', 42),
  (19, 19, 'long_cycle', 'both', 79),
  (20, 20, 'long_cycle', 'both', 78),
  (21, 21, 'long_cycle', 'both', 71),
  (22, 22, 'long_cycle', 'both', 69),
  (23, 23, 'long_cycle', 'both', 66),
  (24, 24, 'long_cycle', 'both', 65),
  (25, 25, 'long_cycle', 'both', 51),
  (26, 26, 'long_cycle', 'both', 46),
  (27, 27, 'long_cycle', 'both', 44),
  (28, 28, 'long_cycle', 'both', 34),
  (29, 29, 'long_cycle', 'both', 31),
  (30, 30, 'long_cycle', 'both', 81),
  (31, 31, 'long_cycle', 'both', 79),
  (32, 32, 'long_cycle', 'both', 79),
  (33, 33, 'long_cycle', 'both', 78),
  (34, 34, 'long_cycle', 'both', 67),
  (35, 35, 'long_cycle', 'both', 67),
  (36, 36, 'long_cycle', 'both', 65),
  (37, 37, 'long_cycle', 'both', 65),
  (38, 38, 'long_cycle', 'both', 61),
  (39, 39, 'long_cycle', 'both', 54),
  (40, 40, 'long_cycle', 'both', 48),
  (41, 41, 'long_cycle', 'both', 47),
  (42, 42, 'long_cycle', 'both', 47),
  (43, 43, 'long_cycle', 'both', 91),
  (44, 44, 'long_cycle', 'both', 85),
  (45, 45, 'long_cycle', 'both', 83),
  (46, 46, 'long_cycle', 'both', 81),
  (47, 47, 'long_cycle', 'both', 78),
  (48, 48, 'long_cycle', 'both', 76),
  (49, 49, 'long_cycle', 'both', 69),
  (50, 50, 'long_cycle', 'both', 64),
  (51, 51, 'long_cycle', 'both', 57),
  (52, 52, 'long_cycle', 'both', 56),
  (53, 53, 'long_cycle', 'both', 99),
  (54, 54, 'long_cycle', 'both', 82),
  (55, 55, 'long_cycle', 'both', 81),
  (56, 56, 'long_cycle', 'both', 75),
  (57, 57, 'long_cycle', 'both', 64),
  (58, 58, 'long_cycle', 'both', 59),
  (59, 59, 'long_cycle', 'both', 58),
  (60, 60, 'long_cycle', 'both', 52),
  (61, 61, 'long_cycle', 'both', 50),
  (62, 62, 'long_cycle', 'both', 40),
  (63, 63, 'long_cycle', 'both', 95),
  (64, 64, 'long_cycle', 'both', 94),
  (65, 65, 'long_cycle', 'both', 92),
  (66, 66, 'long_cycle', 'both', 89),
  (67, 67, 'long_cycle', 'both', 82),
  (68, 68, 'long_cycle', 'both', 63),
  (69, 69, 'long_cycle', 'both', 46),
  (70, 70, 'long_cycle', 'both', 35),
  (71, 71, 'long_cycle', 'both', 63),
  (72, 72, 'long_cycle', 'both', 50),
  (73, 73, 'long_cycle', 'both', 40),
  (74, 74, 'long_cycle', 'both', 39),
  (75, 75, 'long_cycle', 'both', 30),
  (76, 76, 'long_cycle', 'both', 28),
  (77, 77, 'long_cycle', 'both', 28),
  (78, 78, 'long_cycle', 'both', 7),
  (79, 79, 'long_cycle', 'both', 73),
  (80, 80, 'long_cycle', 'both', 50),
  (81, 81, 'long_cycle', 'both', 49),
  (82, 82, 'long_cycle', 'both', 47),
  (83, 83, 'long_cycle', 'both', 39),
  (84, 84, 'long_cycle', 'both', 30),
  (85, 85, 'long_cycle', 'both', 71),
  (86, 86, 'long_cycle', 'both', 62),
  (87, 87, 'long_cycle', 'both', 58),
  (88, 88, 'long_cycle', 'both', 38),
  (89, 89, 'long_cycle', 'both', 28),
  (90, 90, 'long_cycle', 'both', 27),
  (91, 91, 'long_cycle', 'both', 26),
  (92, 92, 'long_cycle', 'both', 85),
  (93, 93, 'long_cycle', 'both', 70),
  (94, 94, 'long_cycle', 'both', 61),
  (95, 95, 'long_cycle', 'both', 53),
  (96, 96, 'long_cycle', 'both', 53),
  (97, 97, 'long_cycle', 'both', 47),
  (98, 98, 'long_cycle', 'both', 46),
  (99, 99, 'long_cycle', 'both', 30),
  (100, 100, 'long_cycle', 'both', 20),
  (101, 101, 'jerk', 'both', 142),
  (102, 102, 'jerk', 'both', 140),
  (103, 103, 'jerk', 'both', 102),
  (104, 104, 'jerk', 'both', 72),
  (105, 105, 'jerk', 'both', 70),
  (106, 106, 'jerk', 'both', 65),
  (107, 107, 'jerk', 'both', 62),
  (108, 108, 'jerk', 'both', 60),
  (109, 109, 'jerk', 'both', 51),
  (110, 110, 'jerk', 'both', 27),
  (111, 111, 'jerk', 'both', 10),
  (112, 112, 'jerk', 'both', 136),
  (113, 113, 'jerk', 'both', 115),
  (114, 114, 'jerk', 'both', 111),
  (115, 115, 'jerk', 'both', 111),
  (116, 116, 'jerk', 'both', 109),
  (117, 117, 'jerk', 'both', 100),
  (118, 118, 'jerk', 'both', 100),
  (119, 119, 'jerk', 'both', 68),
  (120, 120, 'jerk', 'both', 65),
  (121, 121, 'jerk', 'both', 62),
  (122, 122, 'jerk', 'both', 52);

